use_frameworks!

target 'MLWFlexLayout_Example' do
  pod 'MLWFlexLayout', :path => '../'

  target 'MLWFlexLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
